CREATE TABLE `sample_identities` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`sampleId` bigint unsigned NOT NULL,
	`source` enum('external','historical') NOT NULL,
	`sourceReference` text NOT NULL,
	`lot` varchar(200) NOT NULL,
	`antibodyId` varchar(100) NOT NULL,
	`chain` varchar(20) NOT NULL,
	`sequenceId` bigint unsigned,
	`sequenceSnapshot` longtext,
	`sampleSnapshot` text NOT NULL,
	`verification` text NOT NULL,
	`status` enum('review','approved','rejected','retired') NOT NULL DEFAULT 'review',
	`submittedBy` bigint unsigned NOT NULL,
	`submittedByName` varchar(255) NOT NULL,
	`submittedAt` timestamp(3) NOT NULL DEFAULT (now()),
	`requestKey` varchar(36) NOT NULL,
	`requestHash` varchar(64) NOT NULL,
	`reviewedBy` bigint unsigned,
	`reviewedByName` varchar(255),
	`reviewedAt` timestamp(3),
	`reviewNote` text,
	`reviewRequestKey` varchar(36),
	`reviewRequestHash` varchar(64),
	`retiredBy` bigint unsigned,
	`retiredAt` timestamp(3),
	`retirementNote` text,
	`retirementRequestKey` varchar(36),
	`retirementRequestHash` varchar(64),
	CONSTRAINT `sample_identities_id` PRIMARY KEY(`id`),
	CONSTRAINT `sample_identity_request_unique` UNIQUE(`requestKey`)
);
--> statement-breakpoint
CREATE INDEX `sample_identity_sample_idx` ON `sample_identities` (`sampleId`);