import "dotenv/config";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { eq } from "drizzle-orm";
import { users } from "../../db/schema.ts";
import { linearMethodOrder } from "../../contracts/linearMethod.ts";
const url = new URL(process.env.DATABASE_URL!); url.pathname = "/biomap_v15_qa"; process.env.DATABASE_URL = url.toString();
const { getDb } = await import("../../api/queries/connection.ts");
const { appRouter } = await import("../../api/router.ts");
const fixture = JSON.parse(readFileSync("verifier/v18/ui-fixture.json", "utf8"));
const [user] = await getDb().select().from(users).where(eq(users.id, fixture.operatorId));
const api = appRouter.createCaller({ user, req: new Request("http://127.0.0.1:3115"), resHeaders: new Headers() });
const method = await api.workflow.byId({ id: fixture.methodId });
assert.equal(method.nodes.length, 6);
for (const original of fixture.originalNodes) assert.equal(method.nodes.find(node => node.nodeKey === original.nodeKey)?.id, original.id);
const order = linearMethodOrder(method.nodes, method.edges)!;
assert.equal(method.nodes.find(node => node.nodeKey === order[3])?.label, "QA 收获前核对");
assert.equal(method.nodes.find(node => node.nodeKey === "cell_readiness")?.label, "核对细胞状态与培养批次（QA）");
const details = await api.runExecution.details({ runId: fixture.runId });
const completed = details.events.find(event => event.action === "complete_step" && event.nodeKey === "identity");
assert.ok(completed);
const record = JSON.parse(completed.payload);
assert.equal(record.records[0].values.antibody, "QA-UI-CONSTRUCT-018");
assert.equal(record.records[0].sampleIds.length, 2);
assert.equal(record.evidenceIds.length, 0);
const run = await api.labRun.byId({ id: fixture.runId });
assert.equal(run.nodes.find(node => node.nodeKey === "identity")?.status, "completed");
assert.equal(run.nodes.find(node => node.nodeKey === "assembly")?.status, "running");
const batch = [...details.events].reverse().find(event => event.action === "save_step_record" && event.nodeKey === "assembly");
assert.ok(batch);
const pasted = JSON.parse(batch.payload).records;
assert.equal(pasted.length, 2);
assert.deepEqual(pasted.map((row: { values: { reaction: string } }) => row.values.reaction), ["QA-CLONE-A", "QA-CLONE-B"]);
assert.ok(pasted.every((row: { sampleIds: number[] }) => row.sampleIds.length === 1));
console.log(JSON.stringify({ status: "passed", syntheticOnly: true, runId: fixture.runId, methodId: method.id, checks: ["Browser step edits preserve original database node IDs", "New manual step is saved at the chosen position", "Browser draft restored and completed without a file or redundant note", "Recorded values and both sample links persist", "Next step is active"] }, null, 2));
process.exit(0);
