import "dotenv/config";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import * as schema from "../../db/schema.ts";
import { methodNodeSpecSchema, methodSpecSchema } from "../../contracts/method.ts";
const url = new URL(process.env.DATABASE_URL!);
url.pathname = "/biomap_v15_qa";
process.env.DATABASE_URL = url.toString();
assert.equal(new URL(process.env.DATABASE_URL).pathname, "/biomap_v15_qa");
const { migrateDatabase } = await import("../../api/queries/migrate.ts");
await migrateDatabase();
const { getDb } = await import("../../api/queries/connection.ts");
const { appRouter } = await import("../../api/router.ts");
const db = getDb();
const suffix = randomUUID().slice(0, 8);
async function actor(role: "user" | "reviewer" | "viewer") {
  const [row] = await db.insert(schema.users).values({ name: `V15 ${role} ${suffix}`, unionId: `v15:${role}:${suffix}`, role }).$returningId();
  const [user] = await db.select().from(schema.users).where(eq(schema.users.id, row.id));
  return { user, api: appRouter.createCaller({ user, req: new Request("http://localhost:3100"), resHeaders: new Headers() }) };
}
const writer = await actor("user"), reviewer = await actor("reviewer"), viewer = await actor("viewer");
async function methodGuard(id: number) {
  const method = await writer.api.workflow.byId({ id });
  return { expectedSpecHash: method.methodSpecHash, expectedGraphHash: method.graphHash };
}
const [project] = await db.insert(schema.projects).values({ name: `V15 acceptance ${suffix}` }).$returningId();
const [sample] = await db.insert(schema.samples).values({ sku: `V15-${suffix}`, name: "V15 sample", type: "protein", unit: "mL", quantity: 100, projectId: project.id }).$returningId();
const [qualified] = await db.insert(schema.equipment).values({ name: "V15 validated qPCR", category: "analytical", model: "QA instrument" }).$returningId();
const [alternative] = await db.insert(schema.equipment).values({ name: "V15 qualified alternate qPCR", category: "analytical" }).$returningId();
const [wrong] = await db.insert(schema.equipment).values({ name: "V15 incompatible liquid handler", category: "automation" }).$returningId();
const wf = await writer.api.workflow.create({ name: `V15 method ${suffix}`, projectId: project.id });
const graph = { id: wf.id, status: "active" as const, nodes: [{ nodeKey: "qpcr", type: "equipment" as const, label: "Validated qPCR", templateKey: "e_qpcr", posX: 0, posY: 0, params: JSON.stringify({ cycles: 40 }) }], edges: [] };
await writer.api.workflow.saveGraph(graph);
await assert.rejects(writer.api.labRun.launchContext({ workflowId: wf.id }), /已发布版本/);
await assert.rejects(viewer.api.workflow.saveGraph(graph));
const spec = methodSpecSchema.parse({ nodes: { qpcr: methodNodeSpecSchema.parse({ input: "Sample", output: "Ct data", completion: "Raw file recorded", equipmentIds: [qualified.id, alternative.id], qualification: "QA qualification record", manualAllowed: true }) } });
const beforeSpecSave = await methodGuard(wf.id);
await writer.api.workflow.saveMethodSpec({ workflowId: wf.id, ...beforeSpecSave, spec });
assert.equal((await writer.api.workflow.saveMethodSpec({ workflowId: wf.id, ...beforeSpecSave, spec })).replayed, true);
await assert.rejects(writer.api.workflow.saveMethodSpec({ workflowId: wf.id, ...beforeSpecSave, spec: { ...spec, maxSamples: 100 } }), /其他窗口/);
await assert.rejects(writer.api.workflow.submitMethod({ workflowId: wf.id, ...beforeSpecSave }), /其他窗口/);
const release = await writer.api.workflow.submitMethod({ workflowId: wf.id, ...(await methodGuard(wf.id)) });
await assert.rejects(writer.api.workflow.reviewMethod({ id: release.id, decision: "publish", note: "Not a reviewer" }));
await reviewer.api.workflow.reviewMethod({ id: release.id, decision: "publish", note: "Independent review of QA method" });
const context = await writer.api.labRun.launchContext({ workflowId: wf.id });
assert.equal(context.methodRelease.id, release.id);
const base = { workflowId: wf.id, methodReleaseId: release.id, name: "V15 simulation", projectId: project.id, executionMode: "simulation" as const, scheduledStart: new Date(Date.now() + 3600000), scheduledEnd: new Date(Date.now() + 7200000), resources: [{ sampleId: sample.id, role: "sample" as const, amount: 1 }], nodeBindings: [{ nodeKey: "qpcr", equipmentId: qualified.id, params: { cycles: 40 } }], idempotencyKey: randomUUID() };
await assert.rejects(writer.api.labRun.create({ ...base, nodeBindings: [{ nodeKey: "qpcr", equipmentId: wrong.id, params: { cycles: 40 } }] }), /适配确认/);
await assert.rejects(writer.api.labRun.create({ ...base, nodeBindings: [{ nodeKey: "qpcr", equipmentId: qualified.id, params: { cycles: 41 } }] }), /固定参数/);
const draftId = randomUUID();
const payload = { workflowId: wf.id, methodReleaseId: release.id, step: 1, name: base.name, purpose: "QA", projectId: String(project.id), operatorName: writer.user.name!, executionMode: "simulation" as const, scheduledStart: "2026-09-18T10:00", scheduledEnd: "2026-09-18T12:00", selectedResources: { [sample.id]: { role: "sample" as const, amount: 1 } }, sampleOrder: [sample.id], cloningLayoutPlanId: null, skipCloningLayout: false, nodeSetups: {}, idempotencyKey: base.idempotencyKey };
const saved = await writer.api.runDraft.save({ id: draftId, expectedRevision: 0, payload });
assert.equal(saved.revision, 1);
assert.equal((await writer.api.runDraft.save({ id: draftId, expectedRevision: 0, payload })).revision, 1);
await assert.rejects(writer.api.runDraft.save({ id: draftId, expectedRevision: 0, payload: { ...payload, purpose: "stale overwrite" } }), /其他窗口/);
await assert.rejects(writer.api.runDraft.save({ id: draftId, expectedRevision: 1, payload: { ...payload, workflowId: wf.id + 1 } }), /不能更换/);
await writer.api.runDraft.handoff({ id: draftId, expectedRevision: 1, ownerId: reviewer.user.id, note: "Continue preparation" });
await assert.rejects(writer.api.runDraft.save({ id: draftId, expectedRevision: 2, payload }), /交接/);
const restored = await reviewer.api.runDraft.byId({ id: draftId });
assert.equal(restored.payload.selectedResources[sample.id].amount, 1);
assert.equal(restored.revision, 2);
const created = await reviewer.api.labRun.create({ ...base, draftId });
const replay = await reviewer.api.labRun.create({ ...base, draftId });
assert.equal(replay.id, created.id);
assert.equal(replay.repeated, true);
assert.equal((await reviewer.api.runDraft.list()).some(d => d.id === draftId), false);
await assert.rejects(reviewer.api.labRun.create({ ...base, draftId, idempotencyKey: randomUUID() }), /已经生成/);
const before = await reviewer.api.labRun.byId({ id: created.id });
assert.equal(before.integrityValid, true);
assert.equal(before.readiness.summary.blocking, 0);
const graphBefore = await writer.api.workflow.byId({ id: wf.id });
await writer.api.workflow.saveGraph({ ...graph, nodes: [{ ...graph.nodes[0], label: "Unreleased changed label" }] });
await assert.rejects(writer.api.workflow.saveGraph({ ...graph, expectedGraphHash: graphBefore.graphHash }), /其他窗口/);
await assert.rejects(writer.api.workflow.saveMethodSpec({ workflowId: wf.id, expectedSpecHash: graphBefore.methodSpecHash, expectedGraphHash: graphBefore.graphHash, spec }), /方法步骤已在其他窗口/);
const stillPublished = await writer.api.labRun.launchContext({ workflowId: wf.id });
assert.equal(stillPublished.nodes[0].label, "Validated qPCR");
assert.equal((await reviewer.api.labRun.byId({ id: created.id })).snapshotHash, before.snapshotHash);
// Real manual execution uses the existing inventory ledger and independent ELN signature.
const manual = await writer.api.labRun.create({ ...base, executionMode: "manual", scheduledStart: new Date(Date.now() - 60000), scheduledEnd: new Date(Date.now() + 3600000), idempotencyKey: randomUUID(), name: "V15 manual evidence acceptance" });
await db.update(schema.samples).set({ name: "Renamed after run freeze" }).where(eq(schema.samples.id, sample.id));
assert.equal((await writer.api.labRun.byId({ id: manual.id })).resources[0].sampleName, "V15 sample");
const act = async (action: "start" | "complete_step" | "pause" | "resume" | "submit_review" | "approve_results" | "request_equipment" | "approve_equipment", extra: Record<string, unknown> = {}, actor = writer) => {
  const current = await actor.api.labRun.byId({ id: manual.id });
  return actor.api.runExecution.act({ runId: manual.id, expectedRevision: current.revision, idempotencyKey: randomUUID(), action, note: "V15 test evidence and observation", ...extra });
};
await assert.rejects(act("start"), /领料/);
const manualBefore = await writer.api.labRun.byId({ id: manual.id });
const request = await writer.api.sampleRequest.byId({ id: manualBefore.sampleRequestId! });
for (const task of request.tasks) { await writer.api.sampleRequest.claimTask({ taskId: task.id }); await writer.api.sampleRequest.completeTask({ taskId: task.id }); await writer.api.sampleRequest.completeTask({ taskId: task.id }); }
await act("start");
await act("pause");
await assert.rejects(act("complete_step", { nodeKey: "qpcr" }), /暂停/);
await assert.rejects(act("resume"), /核对现场/);
await assert.rejects(act("request_equipment", { nodeKey: "qpcr", equipmentId: wrong.id }), /尚未通过/);
await act("request_equipment", { nodeKey: "qpcr", equipmentId: alternative.id });
const requestEvent = (await writer.api.runExecution.details({ runId: manual.id })).events.findLast(event => event.action === "request_equipment")!;
await assert.rejects(act("approve_equipment", { requestEventId: requestEvent.id }), /另一位/);
await act("approve_equipment", { requestEventId: requestEvent.id }, reviewer);
const replaced = await writer.api.runExecution.details({ runId: manual.id });
assert.equal(replaced.equipmentOverrides.qpcr.equipmentId, alternative.id);
assert.equal((await writer.api.labRun.byId({ id: manual.id })).integrityValid, true);
assert.equal((await writer.api.labRun.byId({ id: manual.id })).nodes[0].equipmentId, qualified.id);
await act("resume", { reconcile: true });
await assert.rejects(act("complete_step", { nodeKey: "qpcr" }), /原始文件/);
const file = await writer.api.runExecution.uploadEvidence({ runId: manual.id, nodeKey: "qpcr", name: "qpcr-raw.csv", contentBase64: Buffer.from("sample,Ct\nV15,22.4\n").toString("base64") });
await act("complete_step", { nodeKey: "qpcr", evidenceIds: [file.id] });
await assert.rejects(act("submit_review"), /缺少结果/);
const current = await writer.api.labRun.byId({ id: manual.id });
const resultInput = { runId: manual.id, expectedRevision: current.revision, idempotencyKey: randomUUID(), nodeKey: "qpcr", sampleId: sample.id, outcome: "pass" as const, value: "22.4", unit: "Ct", evidenceId: file.id, note: "Within QC range" };
const recorded = await writer.api.runExecution.recordResult(resultInput);
assert.equal((await writer.api.runExecution.recordResult(resultInput)).resultId, recorded.resultId);
const corrected = await writer.api.runExecution.recordResult({ ...resultInput, expectedRevision: recorded.revision, idempotencyKey: randomUUID(), value: "22.5", note: "Corrected transcription from raw file" });
const correctionHistory = await writer.api.runExecution.details({ runId: manual.id });
assert.equal(correctionHistory.results.find(row => row.id === recorded.resultId)!.value, "22.4");
assert.equal(correctionHistory.currentResults[0].supersedesId, recorded.resultId);
assert.equal(correctionHistory.currentResults[0].id, corrected.resultId);
const submitted = await act("submit_review");
assert.ok(submitted.experimentId);
await assert.rejects(reviewer.api.experiment.sign({ id: submitted.experimentId!, meaning: "reviewed_and_approved", confirmation: true }), /关联实验任务/);
const generatedRecord = await reviewer.api.experiment.byId({ id: submitted.experimentId! });
assert.equal(generatedRecord.sourceRun?.id, manual.id);
assert.match(generatedRecord.content!, /样本结果 \/ Sample results/);
assert.ok(generatedRecord.content!.includes(`V15-${suffix}`));
assert.ok(generatedRecord.content!.includes("V15 sample"));
await assert.rejects(act("approve_results"), /另一位/);
const detail = await reviewer.api.runExecution.details({ runId: manual.id });
await assert.rejects(act("approve_results", { expectedExperimentRevision: detail.experiment!.revision + 1 }, reviewer), /记录已更新/);
await act("approve_results", { expectedExperimentRevision: detail.experiment!.revision }, reviewer);
const afterManual = await reviewer.api.runExecution.details({ runId: manual.id });
assert.equal(afterManual.execution!.resultState, "approved");
assert.equal(afterManual.experiment!.status, "signed");
await assert.rejects(writer.api.runExecution.recordResult({ ...resultInput, expectedRevision: (await writer.api.labRun.byId({ id: manual.id })).revision, idempotencyKey: randomUUID() }), /不允许修改/);
const flow = (await writer.api.labRun.byId({ id: manual.id })).dataFlow;
assert.equal(flow.resultState.status, "approved");
assert.ok(flow.nodes.some(node => node.kind === "result"));
const reworkInput = { runId: manual.id, sampleIds: [sample.id], reason: "QA selected-sample repeat", idempotencyKey: randomUUID() };
const rework = await writer.api.runExecution.prepareRework(reworkInput);
assert.equal((await writer.api.runExecution.prepareRework(reworkInput)).draftId, rework.draftId);
const reworkDraft = await writer.api.runDraft.byId({ id: rework.draftId });
assert.equal(reworkDraft.payload.reworkSource!.runId, manual.id);
await assert.rejects(writer.api.runDraft.save({ id: rework.draftId, expectedRevision: reworkDraft.revision, payload: { ...reworkDraft.payload, reworkSource: undefined } }), /来源必须保留/);
assert.equal((await writer.api.runExecution.details({ runId: manual.id })).experiment!.status, "signed");
await assert.rejects(writer.api.labRun.create({ ...base, executionMode: "manual", draftId: rework.draftId, idempotencyKey: randomUUID() }), /保留草稿/);
await reviewer.api.workflow.reviewMethod({ id: release.id, decision: "retire", note: "QA retirement" });
await assert.rejects(writer.api.labRun.launchContext({ workflowId: wf.id }), /已发布版本/);
const [stock] = await db.select().from(schema.samples).where(eq(schema.samples.id, sample.id));
assert.equal(Number(stock.quantity), 99);
console.log(JSON.stringify({ status: "passed", cases: ["manual start blocked before issue", "idempotent inventory issue", "pause and physical reconciliation", "required original evidence", "required sample results", "immutable result corrections", "independent review", "linked ELN cannot bypass task review", "human-readable generated ELN", "stale ELN revision rejected", "permanent ELN signature", "result lineage projection", "independent equipment replacement", "frozen plan preserved through deviation", "frozen sample identity displayed", "partial-sample rework draft idempotency", "signed parent unchanged"], manualRunId: manual.id, experimentId: submitted.experimentId }));
console.log(JSON.stringify({ status: "passed", cases: ["legacy publication gate", "requirements conflict and retry", "stale requirements submission rejected", "requirements detect concurrent graph changes", "viewer/author/reviewer permissions", "instrument qualification", "fixed parameters", "draft conflict and retry", "handoff access", "draft-to-run atomic closure", "run creation idempotency", "immutable method version", "retirement", "simulation stock unchanged"], workflowId: wf.id, runId: created.id, database: "biomap_v15_qa" }));
process.exit(0);
