import "dotenv/config";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { eq } from "drizzle-orm";
import { users } from "../../db/schema.ts";
import { latestStepRecord } from "../../contracts/stepRecords.ts";
const url = new URL(process.env.DATABASE_URL!); url.pathname = "/biomap_v15_qa"; process.env.DATABASE_URL = url.toString();
const { getDb } = await import("../../api/queries/connection.ts");
const { appRouter } = await import("../../api/router.ts");
const [user] = await getDb().select().from(users).where(eq(users.id, 54));
const api = appRouter.createCaller({ user, req: new Request("http://127.0.0.1:3115"), resHeaders: new Headers() });
const fixture = JSON.parse(readFileSync("verifier/v20/reuse-fixture.json", "utf8"));
const details = await api.runExecution.details({ runId: fixture.runId });
const rows = latestStepRecord(details.events, "transfection").rows;
assert.equal(rows.length, 1);
assert.deepEqual(rows[0].sampleIds, [212, 213]);
assert.deepEqual(rows[0].values, { cultureLot: "QA-cultureLot-V20", heavyPlasmid: "QA-HC-7a9b6fe9", lightPlasmid: "QA-LC-7a9b6fe9" });
const run = await api.labRun.byId({ id: fixture.runId });
assert.ok(run.integrityValid);
assert.equal(run.nodes.find(node => node.nodeKey === "transfection")?.status, "running");
assert.ok((await api.labRun.byId({ id: 64 })).integrityValid);
console.log("PASS: UI-saved batch/chain lots persisted, measurements and time remain blank, step remains in progress; both current and prior RunPlan integrity preserved.");
process.exit(0);
