import { useI18n } from "@/i18n";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { MethodSpec, MethodNodeSpec } from "@contracts/method";
import { measurementSchema, methodOutputSchema, methodStageSchema, outputTypeSchema } from "@contracts/methodOutputs";
import { antibodyStepRecords } from "@contracts/antibodyStepRecords";
const stageLabels = { cloning: "分子克隆", expression: "转染表达", purification: "抗体纯化", characterization: "抗体表征" };
const typeLabels = { plasmid: "质粒", cell_line: "细胞株", protein: "蛋白", antibody: "抗体", other: "其他" };
const selectClass = "mt-1 block w-full rounded border bg-white p-2 text-sm";
export function ScientificMethod({ spec, editing, change }: { spec: MethodSpec; editing: boolean; change: (value: MethodSpec) => void }) {
 const { t } = useI18n();
 if (!editing) return spec.stage ? <div className="rounded-lg border p-3 text-sm"><strong>{t(stageLabels[spec.stage])}</strong><p className="mt-1">{t("SOP 编号与版本")}：{spec.protocol?.reference} · {spec.protocol?.version}</p><p>{t("允许的输入类型")}：{spec.inputTypes?.map(type => t(typeLabels[type])).join(" · ")}</p></div> : null;
 return <details><summary className="cursor-pointer text-sm">{t("研发阶段与 SOP")}</summary><div className="mt-3 grid gap-3 md:grid-cols-2">
   <Label>{t("研发阶段")}<select className={selectClass} value={spec.stage ?? ""} onChange={e => change({ ...spec, stage: e.target.value ? methodStageSchema.parse(e.target.value) : null })}><option value="">{t("通用实验方法")}</option>{methodStageSchema.options.map(stage => <option key={stage} value={stage}>{t(stageLabels[stage])}</option>)}</select></Label>
   <Label>{t("SOP 编号")}<Input value={spec.protocol?.reference ?? ""} onChange={e => change({ ...spec, protocol: { ...spec.protocol, reference: e.target.value, version: spec.protocol?.version ?? "" } })}/></Label>
   <Label>{t("SOP 版本")}<Input value={spec.protocol?.version ?? ""} onChange={e => change({ ...spec, protocol: { ...spec.protocol, reference: spec.protocol?.reference ?? "", version: e.target.value } })}/></Label>
   <fieldset><legend className="mb-2 text-sm font-medium">{t("允许的输入类型")}</legend><div className="flex flex-wrap gap-3">{outputTypeSchema.options.map(type => <label className="flex gap-2 text-sm" key={type}><input type="checkbox" checked={spec.inputTypes.includes(type)} onChange={e => change({ ...spec, inputTypes: e.target.checked ? [...spec.inputTypes, type] : spec.inputTypes.filter(value => value !== type) })}/>{t(typeLabels[type])}</label>)}</div></fieldset>
   {spec.stage && <div className="space-y-2 md:col-span-2"><Button size="sm" variant="outline" disabled={!Object.entries(antibodyStepRecords[spec.stage]).some(([key]) => spec.nodes[key] && !spec.nodes[key].record)} onClick={() => change({ ...spec, nodes: Object.fromEntries(Object.entries(spec.nodes).map(([key, rule]) => [key, !rule.record && antibodyStepRecords[spec.stage!][key] ? { ...rule, record: antibodyStepRecords[spec.stage!][key] } : rule])) })}>{t("补齐本阶段的步骤记录表")}</Button><p className="text-xs text-muted-foreground">{t("为匹配的步骤添加记录字段，保留已配置的记录表和原始文件要求。")}</p></div>}
 </div></details>;
}
export function ScientificStep({ rule, editing, change }: { rule: MethodNodeSpec; editing: boolean; change: (value: Partial<MethodNodeSpec>) => void }) {
 const { t, lang } = useI18n();
 const output = rule.produces;
 const metrics = rule.measurements ?? [];
 if (!editing) return (metrics.length || output) ? <div className="space-y-2 rounded border bg-slate-50 p-3 text-sm">{output && <p>{t("登记产物")}：{lang === "en" ? output.labelEn || output.label : output.label} · {output.unit} · {output.minCount}–{output.maxCount}</p>}{metrics.length > 0 && <><p>{t(rule.resultsOn === "outputs" ? "逐产物结果" : "逐输入样本结果")}</p><ul className="list-disc pl-5">{metrics.map(metric => <li key={metric.key}>{lang === "en" ? metric.labelEn || metric.label : metric.label} · {metric.unit} · {t(metric.required ? "必填" : "选填")}{(metric.min !== undefined || metric.max !== undefined) && ` · ${metric.min ?? "−∞"} ~ ${metric.max ?? "+∞"}`}</li>)}</ul></>}</div> : null;
 return <details><summary className="cursor-pointer text-sm">{t("产物登记和结果指标")}</summary><div className="mt-3 space-y-4 rounded border p-4">
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={!!output} onChange={e => change(e.target.checked ? { produces: methodOutputSchema.parse({ label: t("新产物"), type: "protein", unit: "mL", relation: "expressed_from" }), resultsOn: "outputs", resultRequired: true } : { produces: null, resultsOn: "inputs" })}/>{t("此步骤产生需要入库的新样本")}</label>
   {output && <div className="space-y-3"><div className="grid gap-3 md:grid-cols-2">
     <Label>{t("产物名称")}<Input value={output.label} onChange={e => change({ produces: { ...output, label: e.target.value } })}/></Label>
     <Label>{t("产物英文名称")}<Input value={output.labelEn} onChange={e => change({ produces: { ...output, labelEn: e.target.value } })}/></Label>
     <Label>{t("产物类型")}<select className={selectClass} value={output.type} onChange={e => change({ produces: { ...output, type: outputTypeSchema.parse(e.target.value) } })}>{outputTypeSchema.options.map(type => <option key={type} value={type}>{t(typeLabels[type])}</option>)}</select></Label>
     <Label>{t("产物计量单位")}<Input value={output.unit} onChange={e => change({ produces: { ...output, unit: e.target.value } })}/></Label>
     {(["minCount", "maxCount"] as const).map(key => <Label key={key}>{t(key === "minCount" ? "最少产物数" : "最多产物数")}<Input type="number" min="1" max="200" value={output[key]} onChange={e => change({ produces: { ...output, [key]: Number(e.target.value) } })}/></Label>)}
     <Label>{t("来源配对要求")}<select className={selectClass} value={output.parentPolicy} onChange={e => change({ produces: { ...output, parentPolicy: e.target.value as typeof output.parentPolicy } })}><option value="selected_inputs">{t("从本批输入中选择")}</option><option value="same_antibody">{t("同一抗体与链别")}</option><option value="paired_hc_lc">{t("同一抗体的重链与轻链配对")}</option></select></Label>
     <Label>{t("样本衍生关系")}<select className={selectClass} value={output.relation} onChange={e => change({ produces: { ...output, relation: e.target.value as typeof output.relation } })}>{Object.entries({ assembled_from: "克隆来源", expressed_from: "表达来源", purified_from: "纯化来源", aliquoted_from: "分装来源" }).map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select></Label>
   </div><label className="flex gap-2 text-sm"><input type="checkbox" checked={output.requiresSequence} onChange={e => change({ produces: { ...output, requiresSequence: e.target.checked } })}/>{t("必须关联构建体序列")}</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={output.requireAllInputs} onChange={e => change({ produces: { ...output, requireAllInputs: e.target.checked } })}/>{t("每份输入都必须有对应产物")}</label>
   <p className="text-sm font-medium">{t("产物必须记录的字段")}</p>{output.requiredMetadata.map((field, index) => <div className="grid gap-2 md:grid-cols-4" key={index}><Label>{t("字段标识")}<Input value={field.key} onChange={e => change({ produces: { ...output, requiredMetadata: output.requiredMetadata.map((item, i) => i === index ? { ...item, key: e.target.value } : item) } })}/></Label><Label>{t("字段名称")}<Input value={field.label} onChange={e => change({ produces: { ...output, requiredMetadata: output.requiredMetadata.map((item, i) => i === index ? { ...item, label: e.target.value } : item) } })}/></Label><Label>{t("英文名称")}<Input value={field.labelEn} onChange={e => change({ produces: { ...output, requiredMetadata: output.requiredMetadata.map((item, i) => i === index ? { ...item, labelEn: e.target.value } : item) } })}/></Label><Button variant="ghost" onClick={() => change({ produces: { ...output, requiredMetadata: output.requiredMetadata.filter((_, i) => i !== index) } })}>{t("移除此记录字段")}</Button></div>)}<Button variant="outline" onClick={() => change({ produces: { ...output, requiredMetadata: [...output.requiredMetadata, { key: `field_${output.requiredMetadata.length + 1}`, label: "", labelEn: "" }] } })}>{t("添加记录字段")}</Button></div>}
   <div className="space-y-3 border-t pt-3"><p className="text-sm font-medium">{t(output ? "逐产物结果" : "逐输入样本结果")}</p>{metrics.map((metric, index) => <div key={index} className="space-y-3 rounded border p-3"><div className="grid gap-3 md:grid-cols-3">
     <Label>{t("指标标识")}<Input value={metric.key} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, key: e.target.value } : item) })}/></Label>
     <Label>{t("指标名称")}<Input value={metric.label} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, label: e.target.value } : item) })}/></Label>
     <Label>{t("英文名称")}<Input value={metric.labelEn} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, labelEn: e.target.value } : item) })}/></Label>
     <Label>{t("记录类型")}<select className={selectClass} value={metric.kind} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, kind: e.target.value as "number" | "text" } : item) })}><option value="number">{t("数值")}</option><option value="text">{t("文字判定")}</option></select></Label>
     <Label>{t("单位")}<Input value={metric.unit} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, unit: e.target.value } : item) })}/></Label>
     {metric.kind === "number" && (["min", "max"] as const).map(bound => <Label key={bound}>{t(bound === "min" ? "合格范围下限（选填）" : "合格范围上限（选填）")}<Input type="number" value={metric[bound] ?? ""} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, [bound]: e.target.value === "" ? undefined : Number(e.target.value) } : item) })}/></Label>)}
   </div><div className="flex gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={metric.required} onChange={e => change({ measurements: metrics.map((item, i) => i === index ? { ...item, required: e.target.checked } : item) })}/>{t("必填结果")}</label><Button variant="ghost" onClick={() => change({ measurements: metrics.filter((_, i) => i !== index) })}>{t("移除此指标")}</Button></div></div>)}<Button variant="outline" onClick={() => change({ resultRequired: true, measurements: [...metrics, measurementSchema.parse({ key: `metric_${metrics.length + 1}`, label: t("新指标") })] })}>{t("添加结果指标")}</Button><p className="text-xs text-muted-foreground">{t("阈值应来自本方法批准的标准；未设置范围时由复核人依据 SOP 判断。")}</p></div>
 </div></details>;
}
